# Generated by Django 2.0.7 on 2018-12-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiendas',
            name='estado',
            field=models.IntegerField(default=0),
        ),
    ]
